version: '3.0'

services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - '8080:8080'
      - '50000:50000'
    restart: unless-stopped
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins-net
volumes:
  jenkins_home:
networks:
  jenkins-net: